// layout.tsx
import type { Metadata } from "next";
import "./globals.css"; // Ensure this is the path to your global CSS

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "'Open Sans', sans-serif" }}>
        {children}
      </body>
    </html>
  );
}
